# Generated by Django 4.2.7 on 2026-01-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruiter_name', models.CharField(max_length=200)),
                ('recruiter_email', models.EmailField(max_length=254)),
                ('recruiter_company', models.CharField(max_length=200)),
                ('recruiter_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('job_title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('work_type', models.CharField(choices=[('remote', 'Remote'), ('onsite', 'On-site'), ('hybrid', 'Hybrid')], default='remote', max_length=50)),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('start_date', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('bio', models.TextField()),
                ('skills_summary', models.TextField(help_text='Comma-separated list of key skills')),
                ('experience_summary', models.TextField(help_text='Brief summary of experience')),
                ('availability', models.CharField(default='Available for opportunities', max_length=100)),
                ('preferred_roles', models.TextField(help_text='Preferred job roles/positions')),
                ('salary_expectation', models.CharField(blank=True, max_length=100, null=True)),
                ('work_preference', models.CharField(choices=[('remote', 'Remote'), ('onsite', 'On-site'), ('hybrid', 'Hybrid'), ('any', 'Any')], default='any', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Personal Information',
            },
        ),
    ]
