# Generated by Django 4.2.7 on 2026-01-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_joboffer_personalinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotTrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField(help_text='Example user message/question')),
                ('intent', models.CharField(choices=[('greeting', 'Greeting'), ('about', 'About/Information'), ('skills', 'Skills'), ('experience', 'Experience'), ('contact', 'Contact Info'), ('availability', 'Availability'), ('job_offer', 'Job Offer'), ('default', 'Default/General')], help_text='Intent category', max_length=50)),
                ('response', models.TextField(help_text='Expected response for this message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Chatbot Training Data',
                'ordering': ['intent', 'created_at'],
            },
        ),
    ]
