# Generated by Django 4.2.7 on 2026-01-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_chatbottrainingdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Unique session identifier', max_length=255, unique=True)),
                ('conversation_state', models.CharField(choices=[('initial', 'Initial Greeting'), ('linkedin_question', 'LinkedIn Question'), ('github_question', 'GitHub Question'), ('email_question', 'Email Question'), ('normal', 'Normal Conversation'), ('job_offer_flow', 'Job Offer Flow')], default='initial', max_length=50)),
                ('conversation_history', models.JSONField(default=list, help_text='List of conversation messages')),
                ('context', models.JSONField(default=dict, help_text='Additional context data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
